### ISSUE TITLE
ProcessError: Cloning into

### ISSUE THREAD

**Issue by npmrun** [alex-page/blazing-fast-gh-pages-deploy#10]
![image](https://user-images.githubusercontent.com/62639956/89257390-9f854980-d658-11ea-95b5-b1e8eed03e5f.png)
can i ask how can i deal this?
it is my problem?

**Comment by alex-page** [comment]
I have not seen this before. Do you have a repo that is open source that I can look at?

**Comment by npmrun** [comment]
sorry, i am late.
i am not familiar with github actions.

https://github.com/npmrun/xyx-ui/actions/runs/199370787

**Comment by alex-page** [comment]
Hey @npmrun I think it is an issue with the GitHub access token. Can you try recreating your secret?

It looks like the branch is being made and has some site data in it. https://github.com/npmrun/xyx-ui/tree/gh-pages

**Comment by npmrun** [comment]
This branch is from my ccomputer.
I used npm library `gh-pages`。
sorry,I think it is so strange!
Forgive me  , I give up! :triumph:
