### ISSUE TITLE
PAT scopes

### ISSUE THREAD

**Issue by telepibe** [alex-page/blazing-fast-gh-pages-deploy#11]
Hi! Thank you for this action.
Do you know the minimum scopes I need to grant to the PAT for this to work?

**Comment by alex-page** [comment]
Hey @telepibe it depends on the repository and where it lives. If it's open source and you own it, you normally need:
` repo - Full control of private repositories`.

If it belongs to an organisation or somebody else you may need them to create it or `admin:org`.

**Comment by telepibe** [comment]
> If it's open source and you own it

I should have started with that. Yeah, I own it but currently is a private repo. But I'm going to change visibility in the near future.
I was wondering if perhaps I could get away with only `repo:status` and `repo_deployment`

Thank you again (and for the quick reply!).

**Comment by alex-page** [comment]
You can only deploy private repos to GitHub pages with a paid account. This might be the issue you are noticing. I am going to close this issue but let me know if you have any problems!
